version: "3.2"
services:
  backend:
    build: 
        context: .
        dockerfile: dockerfile
    ports:
    - "5000:5000"
    network_mode: "host"
  redis:
    image: redis
    ports:
    - "6379:6379"
volumes:
  app-volume: